In [1]:
%pwd

'C:\\Users\\Hp\\Downloads\\projects\\python'

In [2]:
import	pandas	as	pd
import	numpy	as	np
from	datetime	import	datetime,	timedelta
#	Show	more	rows/columns	in	outputs	so	tables	aren't	cut	off
pd.set_option("display.max_columns",	None)
pd.set_option("display.width",	160)
print("Libraries	loaded.	pandas	version:",	pd.__version__)

# A single "today" reference we'll reuse anywhere we need the current date
today = pd.Timestamp.now().normalize()
print("Today's date reference:", today.date())

Libraries	loaded.	pandas	version: 3.0.3
Today's date reference: 2026-09-17

In [3]:
# loading the data
branch = pd.read_csv("branch.csv")

In [4]:
print(branch.shape)

(5, 4)

In [5]:
branch

  branch_id manager_id branch_address    contact_no
0      B001       E109    123 Main St  919099988676
1      B002       E109     456 Elm St  919099988677
2      B003       E109     789 Oak St  919099988678
3      B004       E110    567 Pine St  919099988679
4      B005       E110   890 Maple St  919099988680

In [6]:
employees = pd.read_csv("employees.csv")
books = pd.read_csv("books.csv")
issued_status = pd.read_csv("issued_status.csv")
members = pd.read_csv("members.csv")
return_status = pd.read_csv("return_status.csv")

In [7]:
print(employees.shape)
print(books.shape)
print(issued_status.shape)
print(members.shape)
print(return_status.shape)

(11, 5)
(35, 7)
(35, 6)
(12, 4)
(18, 5)

In [8]:
employees
books
members
issued_status
return_status

   return_id issued_id  return_book_name return_date  return_book_isbn
0      RS101     IS101               NaN  2023-06-06               NaN
1      RS102     IS105               NaN  2023-06-07               NaN
2      RS103     IS103               NaN  2023-08-07               NaN
3      RS104     IS106               NaN  2024-05-01               NaN
4      RS105     IS107               NaN  2024-05-03               NaN
5      RS106     IS108               NaN  2024-05-05               NaN
6      RS107     IS109               NaN  2024-05-07               NaN
7      RS108     IS110               NaN  2024-05-09               NaN
8      RS109     IS111               NaN  2024-05-11               NaN
9      RS110     IS112               NaN  2024-05-13               NaN
10     RS111     IS113               NaN  2024-05-15               NaN
11     RS112     IS114               NaN  2024-05-17               NaN
12     RS113     IS115               NaN  2024-05-19               NaN
13     RS114     IS116               NaN  2024-05-21               NaN
14     RS115     IS117               NaN  2024-05-23               NaN
15     RS116     IS118               NaN  2024-05-25               NaN
16     RS117     IS119               NaN  2024-05-27               NaN
17     RS118     IS120               NaN  2024-05-29               NaN

In [9]:
# .info() = what col. and data type
# .isnull().sum() = are there missing values
books.info()
books.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   isbn          35 non-null     str
 1   book_title    35 non-null     str
 2   category      35 non-null     str
 3   rental_price  35 non-null     float64
 4   status        35 non-null     str
 5   author        35 non-null     str
 6   publisher     35 non-null     str
dtypes: float64(1), str(6)
memory usage: 4.5 KB

isbn            0
book_title      0
category        0
rental_price    0
status          0
author          0
publisher       0
dtype: int64

In [10]:
employees.info()
employees.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   emp_id     11 non-null     str
 1   emp_name   11 non-null     str
 2   position   11 non-null     str
 3   salary     11 non-null     float64
 4   branch_id  11 non-null     str
dtypes: float64(1), str(4)
memory usage: 881.0 bytes

emp_id       0
emp_name     0
position     0
salary       0
branch_id    0
dtype: int64

In [11]:
issued_status.info()
issued_status.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   issued_id         35 non-null     str
 1   issued_member_id  35 non-null     str
 2   issued_book_name  35 non-null     str
 3   issued_date       35 non-null     str
 4   issued_book_isbn  35 non-null     str
 5   issued_emp_id     35 non-null     str
dtypes: str(6)
memory usage: 3.8 KB

issued_id           0
issued_member_id    0
issued_book_name    0
issued_date         0
issued_book_isbn    0
issued_emp_id       0
dtype: int64

In [12]:
return_status.info()
return_status.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   return_id         18 non-null     str
 1   issued_id         18 non-null     str
 2   return_book_name  0 non-null      float64
 3   return_date       18 non-null     str
 4   return_book_isbn  0 non-null      float64
dtypes: float64(2), str(3)
memory usage: 1.2 KB

return_id            0
issued_id            0
return_book_name    18
return_date          0
return_book_isbn    18
dtype: int64

In [13]:
 # dates in issued and return book in text so converting date columns to real dates
issued_status["issued_date"] = pd.to_datetime(issued_status["issued_date"])
return_status["return_date"] = pd.to_datetime(return_status["return_date"])
members["reg_date"] = pd.to_datetime(members["reg_date"])

In [14]:
issued_status.dtypes

issued_id                      str
issued_member_id               str
issued_book_name               str
issued_date         datetime64[us]
issued_book_isbn               str
issued_emp_id                  str
dtype: object

In [15]:
# CRUD Operations (Create, Read, Update, Delete)

In [16]:
# new entry
new_book	=	pd.DataFrame([{
"isbn":	"978-1-60129-456-2",
"book_title":	"To	Kill	a	Mockingbird",
"category":	"Classic",
"rental_price":	6.00,
"status":	"yes",
"author":	"Harper	Lee",
"publisher":	"J.B.	Lippincott	&	Co."
}])
books	=	pd.concat([books,	new_book],	ignore_index=True)
print("Books	table	now	has",	len(books),	"rows")
books.tail(3)

Books	table	now	has 36 rows

                 isbn                book_title category  rental_price status          author                  publisher
33  978-0-7432-4722-5           Angels & Demons  Mystery           7.5    yes       Dan Brown                  Doubleday
34  978-0-7432-7356-4                The Hobbit  Fantasy           7.0    yes  J.R.R. Tolkien  Houghton Mifflin Harcourt
35  978-1-60129-456-2  To\tKill\ta\tMockingbird  Classic           6.0    yes     Harper\tLee   J.B.\tLippincott\t&\tCo.

In [17]:
# updateing member C103 's addres to '125 Oak St' = .loc[row_filter, column] = value
members.loc[members["member_id"] == "C103", "member_addres"] = " 125 Oak St"

members[members["member_id"] == "C103"]

  member_id  member_name member_address   reg_date member_addres
2      C103  Carol Davis     789 Oak St 2021-07-10    125 Oak St

In [18]:
## delete = remove a record , .delete()
# remove the loan record with issued_id = "IS140'
# Tips: there's no .delete() in pandas. So we will keep everything that does not match our condition, using the ~(not) operator to flip a boolean mask

before	=	len(issued_status)
issued_status	=	issued_status[~(issued_status["issued_id"]	==	"IS140")].reset_index(drop=True)
after	=	len(issued_status)
print(f"Rows	before:	{before},	after:	{after}")

Rows	before:	35,	after:	34

In [19]:
#Task 4: Find all books issued by the employee with emp_id = 'E101'.
task4 = issued_status[issued_status["issued_emp_id"] == "E101"]
task4

   issued_id issued_member_id       issued_book_name issued_date   issued_book_isbn issued_emp_id
24     IS130             C106              Moby Dick  2024-04-03  978-0-451-52994-2          E101
25     IS131             C106  To Kill a Mockingbird  2024-04-04  978-0-06-112008-4          E101

In [20]:
# Task 5: List Members Who Have Issued More Than One Book
books_per_member	=	(
issued_status.groupby("issued_member_id")
.size()																							
#	count	rows	in	each	group
.reset_index(name="books_issued")
)
task5	=	books_per_member[books_per_member["books_issued"]	>	1]
task5.sort_values("books_issued",	ascending=False)

  issued_member_id  books_issued
8             C109             7
6             C107             6
4             C105             5
9             C110             5
5             C106             4
1             C102             2
7             C108             2

In [21]:
## Building Derived Summary Tables

In [22]:
# Task 6 - How many times each book has been issued

In [23]:
book_issue_counts = (
    issued_status.merge(books, left_on="issued_book_isbn", right_on="isbn")
    .groupby(["isbn", "book_title"])
    .agg(issue_count=("issued_id", "count"))
    .reset_index()
    .sort_values("issue_count", ascending=False)
)
book_issue_counts

                 isbn                                         book_title  issue_count
26  978-0-679-76489-8               Harry Potter and the Sorcerers Stone            2
22  978-0-525-47535-5                                   The Great Gatsby            2
0   978-0-06-025492-6                          Where the Wild Things Are            1
1   978-0-06-112008-4                              To Kill a Mockingbird            1
4   978-0-09-957807-9                                  A Game of Thrones            1
5   978-0-14-027526-3                               A Tale of Two Cities            1
2   978-0-06-112241-5                                    The Kite Runner            1
3   978-0-06-440055-8                                    Charlotte's Web            1
8   978-0-14-143951-8                                Pride and Prejudice            1
9   978-0-141-44171-6                                          Jane Eyre            1
10  978-0-19-280551-1                                 The Guns of August            1
11  978-0-307-37840-1                                      The Alchemist            1
12  978-0-307-58837-1              Sapiens: A Brief History of Humankind            1
13  978-0-330-25864-8                                        Animal Farm            1
6   978-0-14-044930-3                                      The Histories            1
7   978-0-14-118776-1                      One Hundred Years of Solitude            1
15  978-0-375-41398-8                          The Diary of a Young Girl            1
14  978-0-345-39180-3                                               Dune            1
18  978-0-393-91257-8  Guns, Germs, and Steel: The Fates of Human Soc...            1
16  978-0-385-33312-0                                        The Shining            1
19  978-0-451-52993-5                                     Fahrenheit 451            1
20  978-0-451-52994-2                                          Moby Dick            1
21  978-0-452-28240-7                                    Brave New World            1
17  978-0-393-05081-8             A Peoples History of the United States            1
23  978-0-553-29698-2                             The Catcher in the Rye            1
24  978-0-670-81302-4                                           The Road            1
25  978-0-679-64115-3                                               1984            1
27  978-0-679-77644-3                                            Beloved            1
28  978-0-7432-4722-5                                    Angels & Demons            1
29  978-0-7432-7356-4                                         The Hobbit            1
30  978-0-7432-7357-1  1491: New Revelations of the Americas Before C...            1
31  978-0-7434-7679-3                                          The Stand            1

In [24]:
## Data Analysis : answering bussiness questions

In [25]:
# Task -7 Retrieve All Books in a Specific Category = classic

In [26]:
task7 = books[books["category"] == "Classic"]
task7

                 isbn                book_title category  rental_price status               author                  publisher
0   978-0-553-29698-2    The Catcher in the Rye  Classic           7.0    yes        J.D. Salinger  Little, Brown and Company
1   978-0-330-25864-8               Animal Farm  Classic           5.5    yes        George Orwell              Penguin Books
3   978-0-525-47535-5          The Great Gatsby  Classic           8.0    yes  F. Scott Fitzgerald                   Scribner
4   978-0-141-44171-6                 Jane Eyre  Classic           4.0    yes     Charlotte Bronte           Penguin Classics
17  978-0-14-143951-8       Pride and Prejudice  Classic           5.0    yes          Jane Austen           Penguin Classics
28  978-0-14-027526-3      A Tale of Two Cities  Classic           4.5    yes      Charles Dickens              Penguin Books
30  978-0-451-52994-2                 Moby Dick  Classic           6.5    yes      Herman Melville              Penguin Books
31  978-0-06-112008-4     To Kill a Mockingbird  Classic           5.0    yes           Harper Lee      J.B. Lippincott & Co.
35  978-1-60129-456-2  To\tKill\ta\tMockingbird  Classic           6.0    yes          Harper\tLee   J.B.\tLippincott\t&\tCo.

In [27]:
# Task 8: Find Total Rental Income by Category

In [28]:
income_by_category = (
    books.merge(issued_status, left_on="isbn", right_on="issued_book_isbn")
    .groupby("category")["rental_price"]
    .sum()
    .reset_index(name="total_rental_income")
    .sort_values("total_rental_income", ascending=False)
)
income_by_category

           category  total_rental_income
1           Classic                 53.5
5           History                 49.5
3           Fantasy                 28.5
2         Dystopian                 25.5
4           Fiction                 14.5
6            Horror                 13.0
9   Science Fiction                  8.5
0          Children                  7.5
8           Mystery                  7.5
7  Literary Fiction                  6.5

In [29]:
## Task 9 List Members Who Registered in the Last 1180 Days

In [30]:
# check dates min and max
members["reg_date"].agg(["min",	"max"])

min   2021-05-15
max   2024-06-01
Name: reg_date, dtype: datetime64[us]

In [31]:

recent_cutoff	=	today	-	pd.Timedelta(days=1180)
task9	=	members[members["reg_date"]	>=	recent_cutoff]
task9

   member_id member_name member_address   reg_date member_addres
10      C118         Sam    133 Pine St 2024-06-01           NaN
11      C119        John    143 Main St 2024-05-01           NaN

In [32]:
# Task 10 List Employees with Their Branch Manager's Name and their branch details

In [33]:
managers = employees[["emp_id", "emp_name"]].rename(
    columns={"emp_id": "manager_id", "emp_name": "manager_name"}
)

task10 = (
    employees.merge(branch, on="branch_id")
    .merge(managers, on="manager_id")
)

task10[["emp_id", "emp_name", "position", "salary", "branch_id",
        "branch_address", "contact_no", "manager_name"]]

   emp_id          emp_name   position   salary branch_id branch_address    contact_no     manager_name
0    E101          John Doe      Clerk  60000.0      B001    123 Main St  919099988676  Daniel Anderson
1    E102        Jane Smith      Clerk  45000.0      B002     456 Elm St  919099988677  Daniel Anderson
2    E103      Mike Johnson  Librarian  55000.0      B001    123 Main St  919099988676  Daniel Anderson
3    E104       Emily Davis  Assistant  40000.0      B001    123 Main St  919099988676  Daniel Anderson
4    E105       Sarah Brown  Assistant  42000.0      B001    123 Main St  919099988676  Daniel Anderson
5    E106  Michelle Ramirez  Assistant  43000.0      B001    123 Main St  919099988676  Daniel Anderson
6    E107  Michael Thompson      Clerk  62000.0      B005   890 Maple St  919099988680   Laura Martinez
7    E108    Jessica Taylor      Clerk  46000.0      B004    567 Pine St  919099988679   Laura Martinez
8    E109   Daniel Anderson    Manager  57000.0      B003     789 Oak St  919099988678  Daniel Anderson
9    E110    Laura Martinez    Manager  41000.0      B005   890 Maple St  919099988680   Laura Martinez
10   E111   Christopher Lee  Assistant  65000.0      B005   890 Maple St  919099988680   Laura Martinez

In [34]:
# Task 11. **Create a Table of Books with Rental Price Above a Certain Threshold

In [35]:
expensive_books	=	books[books["rental_price"]	>	7.00].sort_values("rental_price",	ascending=False)
expensive_books

                 isbn                              book_title         category  rental_price status               author         publisher
9   978-0-393-05081-8  A Peoples History of the United States          History           9.0    yes          Howard Zinn  Harper Perennial
22  978-0-345-39180-3                                    Dune  Science Fiction           8.5    yes        Frank Herbert               Ace
3   978-0-525-47535-5                        The Great Gatsby          Classic           8.0    yes  F. Scott Fitzgerald          Scribner
11  978-0-307-58837-1   Sapiens: A Brief History of Humankind          History           8.0     no    Yuval Noah Harari  Harper Perennial
7   978-0-7432-4722-4                       The Da Vinci Code          Mystery           8.0    yes            Dan Brown         Doubleday
8   978-0-09-957807-9                       A Game of Thrones          Fantasy           7.5    yes   George R.R. Martin            Bantam
33  978-0-7432-4722-5                         Angels & Demons          Mystery           7.5    yes            Dan Brown         Doubleday

In [36]:
# Task 12: **Retrieve the List of Books Not Yet Returned**

In [37]:
loans_with_returns = issued_status.merge(return_status, on="issued_id", how="left")

task12 = loans_with_returns[loans_with_returns["return_id"].isna()]
task12[["issued_id", "issued_member_id", "issued_book_name", "issued_date", "issued_emp_id"]]

   issued_id issued_member_id                                   issued_book_name issued_date issued_emp_id
15     IS121             C102                                        The Shining  2024-03-25          E109
16     IS122             C102                                     Fahrenheit 451  2024-03-26          E109
17     IS123             C103                                               Dune  2024-03-27          E109
18     IS124             C104                          Where the Wild Things Are  2024-03-28          E110
19     IS125             C105                                    The Kite Runner  2024-03-29          E110
20     IS126             C105                                    Charlotte's Web  2024-03-30          E110
21     IS127             C105                                            Beloved  2024-03-31          E110
22     IS128             C105                               A Tale of Two Cities  2024-04-01          E110
23     IS129             C105                                          The Stand  2024-04-02          E110
24     IS130             C106                                          Moby Dick  2024-04-03          E101
25     IS131             C106                              To Kill a Mockingbird  2024-04-04          E101
26     IS132             C106                                         The Hobbit  2024-04-05          E106
27     IS133             C107                                    Angels & Demons  2024-04-06          E106
28     IS134             C107                          The Diary of a Young Girl  2024-04-07          E106
29     IS135             C107              Sapiens: A Brief History of Humankind  2024-04-08          E108
30     IS136             C107  1491: New Revelations of the Americas Before C...  2024-04-09          E102
31     IS137             C107                             The Catcher in the Rye  2024-04-10          E103
32     IS138             C108                                   The Great Gatsby  2024-04-11          E104
33     IS139             C109               Harry Potter and the Sorcerers Stone  2024-04-12          E105

In [38]:
# **Task 13: Identify Members with Overdue Books more than 130 days**  
# Write a query to identify members who have overdue books (assume a 30-day return period). Display the member's_id, member's name, book title, issue date, and days overdue.

In [39]:
overdue = (
    issued_status.merge(members, left_on = "issued_member_id", right_on = "member_id")
    .merge(books, left_on = "issued_book_isbn", right_on = "isbn")
    .merge(return_status, on = "issued_id", how = "left")
)
overdue = overdue[overdue["return_date"].isna()].copy()
overdue["days_since_issued"] = (today - overdue ["issued_date"]).dt.days

In [40]:
task13	=	(
	overdue[overdue["days_since_issued"]	>	130]
	[["issued_member_id", "member_name", "book_title", "issued_date", "days_since_issued"]]
	.sort_values("days_since_issued", ascending=False)
)
task13

   issued_member_id     member_name                                         book_title issued_date  days_since_issued
15             C102       Bob Smith                                        The Shining  2024-03-25                906
16             C102       Bob Smith                                     Fahrenheit 451  2024-03-26                905
17             C103     Carol Davis                                               Dune  2024-03-27                904
18             C104     Dave Wilson                          Where the Wild Things Are  2024-03-28                903
19             C105       Eve Brown                                    The Kite Runner  2024-03-29                902
20             C105       Eve Brown                                    Charlotte's Web  2024-03-30                901
21             C105       Eve Brown                                            Beloved  2024-03-31                900
22             C105       Eve Brown                               A Tale of Two Cities  2024-04-01                899
23             C105       Eve Brown                                          The Stand  2024-04-02                898
24             C106    Frank Thomas                                          Moby Dick  2024-04-03                897
25             C106    Frank Thomas                              To Kill a Mockingbird  2024-04-04                896
26             C106    Frank Thomas                                         The Hobbit  2024-04-05                895
27             C107    Grace Taylor                                    Angels & Demons  2024-04-06                894
28             C107    Grace Taylor                          The Diary of a Young Girl  2024-04-07                893
29             C107    Grace Taylor              Sapiens: A Brief History of Humankind  2024-04-08                892
30             C107    Grace Taylor  1491: New Revelations of the Americas Before C...  2024-04-09                891
31             C107    Grace Taylor                             The Catcher in the Rye  2024-04-10                890
32             C108  Henry Anderson                                   The Great Gatsby  2024-04-11                889
33             C109    Ivy Martinez               Harry Potter and the Sorcerers Stone  2024-04-12                888

In [41]:
# **Task 14: Update Book Status on Return**  
# Write a query to update the status of books in the books table to "Yes" when they are returned (based on entries in the return_status table).

In [42]:
#1.1 check aready this book quality col. present or not 
print("book_quality" in return_status.columns)
return_status.head()

False

  return_id issued_id  return_book_name return_date  return_book_isbn
0     RS101     IS101               NaN  2023-06-06               NaN
1     RS102     IS105               NaN  2023-06-07               NaN
2     RS103     IS103               NaN  2023-08-07               NaN
3     RS104     IS106               NaN  2024-05-01               NaN
4     RS105     IS107               NaN  2024-05-03               NaN

In [43]:
#1.2 doesn't exist. 
return_status["book_quality"] = "Good"

damaged_ids = ["IS109", "IS112", "IS115"] # returns the library's notes flagged as damaged
return_status.loc[return_status["issued_id"].isin(damaged_ids), "book_quality"] = "Damaged"

return_status[return_status["book_quality"] == "Damaged"]

   return_id issued_id  return_book_name return_date  return_book_isbn book_quality
6      RS107     IS109               NaN  2024-05-07               NaN      Damaged
9      RS110     IS112               NaN  2024-05-13               NaN      Damaged
12     RS113     IS115               NaN  2024-05-19               NaN      Damaged

In [44]:
def	process_return(return_id,	issued_id,	book_quality,	books_df,	issued_df,	returns_df):
				"""Record	a	book	return	and	mark	the	book	as	available	again."""
				loan	=	issued_df[issued_df["issued_id"]	==	issued_id].iloc[0]
				isbn	=	loan["issued_book_isbn"]
				book_name	=	loan["issued_book_name"]
				new_return	=	pd.DataFrame([{
								"return_id":	return_id,
								"issued_id":	issued_id,
								"return_book_name":	book_name,
								"return_date":	pd.Timestamp.now().normalize(),
								"return_book_isbn":	isbn,
								"book_quality":	book_quality,
				}])
				returns_df	=	pd.concat([returns_df,	new_return],	ignore_index=True)
				books_df.loc[books_df["isbn"]	==	isbn,	"status"]	=	"yes"
				print(f"Recorded	return	for	'{book_name}'	—	condition:	{book_quality}")
				return	books_df,	returns_df
#	Try	it	out	on	a	currently-unreturned	loan
books,	return_status	=	process_return("RS150",	"IS121",	"Good",	books,	issued_status,	return_status)
return_status.tail(3)

Recorded	return	for	'The Shining'	—	condition:	Good

   return_id issued_id return_book_name return_date   return_book_isbn book_quality
16     RS117     IS119              NaN  2024-05-27                NaN         Good
17     RS118     IS120              NaN  2024-05-29                NaN         Good
18     RS150     IS121      The Shining  2026-09-17  978-0-385-33312-0         Good

In [45]:
# **Task 15: Branch Performance Report**  
# Create a query that generates a performance report for each branch, showing the number of books issued, the number of books returned, and the total revenue generated from book rentals.

In [46]:
branch_activity = (
    issued_status.merge(employees, left_on = "issued_emp_id", right_on = "emp_id")
    .merge(branch, on = "branch_id")
    .merge(return_status, on = "issued_id", how = "left")
    .merge(books, left_on = "issued_book_isbn", right_on = "isbn")
)

In [47]:
branch_report = (
    branch_activity.groupby("branch_id")
    .agg(
        books_issued = ("issued_id", "count"),
        books_returned = ("return_id", "count"),
        total_revenue = ("rental_price", "sum"),
    )
    .reset_index()
    .sort_values("total_revenue", ascending = False)
)
branch_report

  branch_id  books_issued  books_returned  total_revenue
0      B001            17               9          111.5
4      B005             9               3           50.0
3      B004             4               3           26.5
2      B003             3               1           20.0
1      B002             1               0            6.5

In [48]:
# **Task 16: CTAS: Create a Table of Active Members**  
#Use the CREATE TABLE AS (CTAS) statement to create a new table active_members containing members who have issued at least one book in the last 2 months.

In [49]:
cutoff	=	today	-	pd.DateOffset(months=2)
active_member_ids	=	issued_status.loc[issued_status["issued_date"]	>=	cutoff,	"issued_member_id"].unique()
active_members	=	members[members["member_id"].isin(active_member_ids)]
active_members

Empty DataFrame
Columns: [member_id, member_name, member_address, reg_date, member_addres]
Index: []

In [50]:
reference_date	=	issued_status["issued_date"].max()
cutoff	=	reference_date	-	pd.DateOffset(months=2)
active_member_ids	=	issued_status.loc[issued_status["issued_date"]	>=	cutoff,	"issued_member_id"].unique()
active_members	=	members[members["member_id"].isin(active_member_ids)]
print(f"Reference	date	used:	{reference_date.date()}		|		cutoff:	{cutoff.date()}")
active_members

Reference	date	used:	2024-04-12		|		cutoff:	2024-02-12

  member_id     member_name member_address   reg_date member_addres
0      C101   Alice Johnson    123 Main St 2021-05-15           NaN
1      C102       Bob Smith     456 Elm St 2021-06-20           NaN
2      C103     Carol Davis     789 Oak St 2021-07-10    125 Oak St
3      C104     Dave Wilson    567 Pine St 2021-08-05           NaN
4      C105       Eve Brown   890 Maple St 2021-09-25           NaN
5      C106    Frank Thomas   234 Cedar St 2021-10-15           NaN
6      C107    Grace Taylor  345 Walnut St 2021-11-20           NaN
7      C108  Henry Anderson   456 Birch St 2021-12-10           NaN
8      C109    Ivy Martinez     567 Oak St 2022-01-05           NaN
9      C110     Jack Wilson    678 Pine St 2022-02-25           NaN

In [51]:
# **Task 17: Find Employees with the Most Book Issues Processed**  
# Write a query to find the top 3 employees who have processed the most book issues. Display the employee name, number of books processed, and their branch.

In [52]:
task17 = (
    issued_status.merge(employees, left_on = "issued_emp_id", right_on = "emp_id")
    .merge(branch, on = "branch_id")
    .groupby(["emp_id", "emp_name", "branch_id"])
    .size()
    .reset_index(name = "books_processed")
    .sort_values("books_processed", ascending = False)
    .head(3)
)
task17

  emp_id          emp_name branch_id  books_processed
9   E110    Laura Martinez      B005                6
5   E106  Michelle Ramirez      B001                6
7   E108    Jessica Taylor      B004                4

In [53]:
# **Task 18: Identify Members Issuing High-Risk Books**  
# Write a query to identify members who have issued books more than twice with the status "damaged" in the books table. Display the member name, book title, and the number of times they've issued damaged books.

In [54]:
damaged_loans = (
				issued_status.merge(books, left_on="issued_book_isbn", right_on="isbn")
							 .merge(members,	left_on="issued_member_id",	right_on="member_id")
							.merge(return_status,	on="issued_id")
)
damaged_loans =	damaged_loans[damaged_loans["book_quality"]	==	"Damaged"]
damage_counts =	(
    damaged_loans.groupby(["member_id",	"member_name"])
				 .size()
				 .reset_index(name="damaged_returns")
)
print("All members with at least one damaged return:")
display(damage_counts)
task18	= damage_counts[damage_counts["damaged_returns"]	>	2]
print("\nMembers exceeding the 2-damaged-book threshold:")
task18

All members with at least one damaged return:

  member_id   member_name  damaged_returns
0      C109  Ivy Martinez                3

Members exceeding the 2-damaged-book threshold:

  member_id   member_name  damaged_returns
0      C109  Ivy Martinez                3

In [55]:
###**Task 19: Stored Procedure**
##Objective:
# Create a stored procedure to manage the status of books in a library system.
# Description:
# Write a stored procedure that updates the status of a book in the library based on its issuance. The procedure should function as follows:
# The stored procedure should take the book_id as an input parameter.
# The procedure should first check if the book is available (status = 'yes').
# If the book is available, it should be issued, and the status in the books table should be updated to 'no'.
# If the book is not available (status = 'no'), the procedure should return an error message indicating that the book is currently not available.

In [56]:
def issue_book(issued_id, member_id, isbn, emp_id, books_df, issued_df):
    """Issue a book to a member if it is currently availble."""
    match = books_df.loc[books_df["isbn"] == isbn, "status"]
    if match.empty:
        print(f"No book found with ISBN {isbn}")
        return books_df, issued_df
        if match.iloc[0] == "yes":
            book_title = books_df.loc[books_df["isbn"] == isbn, "book_title"].iloc[0]
        new_loan = pd.DataFrame([{
        "issued_id": issued_id,
        "issued_member_id": member_id,
        "issued_book_name": book_title,
        "issued_data": pd.Timestamp.now().normalize(),
        "issued_book_isbn": isbn,
        "issued_emp_id": emp_id,
    }])
        issued_df =	pd.concat([issued_df,	new_loan],	ignore_index=True)
        books_df.loc[books_df["isbn"] == isbn, "status"] =	"no"
        print(f"'{book_title}' issued successfully to member {member_id}")
    else:
        print(f"Sorry	—	the	book	with	ISBN	{isbn}	is	currently	unavailable")
        return	books_df,	issued_df
#	Try	issuing	a	book	that	IS	available
books,	issued_status	=	issue_book("IS200",	"C108",	"978-1-60129-456-2",	"E104",	books,	issued_status)
#	Try	issuing	a	book	that	is	NOT	available	(status	was	flipped	to	'no'	by	the	call	above)
books,	issued_status	=	issue_book("IS201",	"C108",	"978-1-60129-456-2",	"E104",	books,	issued_status)

Sorry	—	the	book	with	ISBN	978-1-60129-456-2	is	currently	unavailable
Sorry	—	the	book	with	ISBN	978-1-60129-456-2	is	currently	unavailable

In [58]:
# **Task 20: Create Table As Select (CTAS)**
# Objective: Create a CTAS (Create Table As Select) query to identify overdue books and calculate fines.

# Description: Write a CTAS query to create a new table that lists each member and the books they have issued but not returned within 30 days. The table should include:
    #The number of overdue books.
    #The total fines, with each day's fine calculated at $0.50.
    #The number of books issued by each member.
    #The resulting table should show:
    #Member ID
    #Number of overdue books
    #Total fines

In [59]:
overdue_loans = issued_status.merge(return_status, on="issued_id", how="left")
overdue_loans = overdue_loans[overdue_loans["return_id"].isna()].copy()
overdue_loans["days_overdue"] = (today - overdue_loans["issued_date"]).dt.days
overdue_loans = overdue_loans[overdue_loans["days_overdue"] > 30]

fines_report = (
    overdue_loans.groupby("issued_member_id")
    .agg(
        overdue_books = ("issued_id", "count"),
        total_fine = ("days_overdue", lambda days: (days * 0.50).sum()),
    )
    .reset_index()
    .rename(columns={"issued_member_id": "member_id"})
    .sort_values("total_fine", ascending = False)
)
fines_report

  member_id  overdue_books  total_fine
3      C105              5      2250.0
5      C107              5      2230.0
4      C106              3      1344.0
0      C102              1       452.5
1      C103              1       452.0
2      C104              1       451.5
6      C108              1       444.5
7      C109              1       444.0